version: '3'
services:
  web:
    build: .
    image: vehicle-overview
    volumes: 
      - vol1:/vehicle-overview
      - vol2:/vehicle-overview/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:

      DATABASE_URL: postgres://postgres:suryvillalobos@db:5432/gryffinwheels
    links:
      - db
    command: npm start
  db:
    image: postgres:10.4
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gryffinwheels    
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suryvillalobos
volumes:
  db:
  vol1:
  vol2:
  